const auspiciantes = [
    { id: 1, auspiciante: "Aceros Levalle", logo: "aceros_levalle.jpg" },
    { id: 10, auspiciante: "Agroucacha", logo: "agroucacha.jpg" },
    { id: 24, auspiciante: "Armendariz Diesel", logo: "armendariz_diesel.jpg" },
    { id: 25, auspiciante: "Autoservicio El Gato", logo: "autoservicio_el_gato.jpg" },
    { id: 26, auspiciante: "Berra Extintores", logo: "berra_extintores.jpg" },
    { id: 14, auspiciante: "Brasería El Luga", logo: "braseria_el_luga.jpg" },
    { id: 23, auspiciante: "By Vicent Deco & Party", logo: "by_vicent_deco_party.jpg" },
    { id: 27, auspiciante: "Carnes Manso", logo: "carnes_manso.jpg" },
    { id: 28, auspiciante: "Colorshop", logo: "colorshop.jpg" },
    { id: 4, auspiciante: "Corralón González", logo: "corralon_gonzalez.jpg" },
    { id: 5, auspiciante: "Corralón Juan Rosatto", logo: "corralon_rosatto.jpg" },
    { id: 9, auspiciante: "Cruseño Hermanos", logo: "cruseno_hermanos.jpg" },
    { id: 29, auspiciante: "Discesapoli Servicios Agropecuarias", logo: "discesapoli_servicios_agropecuarios.jpg" },
    { id: 30, auspiciante: "Disensa", logo: "disensa.jpg" },
    { id: 16, auspiciante: "El Gauchito", logo: "el_gauchito.jpg" },
    { id: 6, auspiciante: "Estudio Contable Fusta", logo: "estudio_fusta.jpg" },
    { id: 15, auspiciante: "Farmacia Saracco", logo: "farmacia_saracco.jpg" },
    { id: 31, auspiciante: "Farmacia Giménez", logo: "farmacia_gimenez.jpg" },
    { id: 32, auspiciante: "Frigorífico Manzo", logo: "frigorifico_manzo.jpg" },
    { id: 7, auspiciante: "Garatoni Automotores", logo: "garatoni_automotores.jpg" },
    { id: 33, auspiciante: "González Ferretería", logo: "gonzalez_ferreteria.jpg" },
    { id: 20, auspiciante: "Julián Garais Soluciones Agropecuarias", logo: "julian_garais_agropecuarias.jpg" },
    { id: 8, auspiciante: "José Androetto Construcciones", logo: "androetto_construccion.jpg" },
    { id: 34, auspiciante: "Kevin Frutas y Verduras", logo: "kevin_frutas_y_verduras.jpg" },
    { id: 35, auspiciante: "Lands Seguridad", logo: "lands_seguridad.jpg" },
    { id: 11, auspiciante: "Laura Fenoglio Estudio Contable", logo: "laura_fenoglio_contable.jpg" },
    { id: 18, auspiciante: "Maxi Crosio Pulverizaciones Aéreas", logo: "maxi_crosio_pulverizaciones.jpg" },
    { id: 36, auspiciante: "Mr. Clean", logo: "mr_clean.jpg" },
    { id: 17, auspiciante: "Municipalidad de General Levalle", logo: "municipalidad_general_levalle.jpg" },
    { id: 13, auspiciante: "Nutrilev", logo: "nutrilev.jpg" },
    { id: 22, auspiciante: "Pastel Cake de Laura Giraudo", logo: "pastel_cake_laura_giraudo.jpg" },
    { id: 37, auspiciante: "Picolo Hermanos", logo: "p_hermanos.jpg" },
    { id: 38, auspiciante: "Pizza Pippo", logo: "pizza_pippo.jpg" },
    { id: 39, auspiciante: "Quesería La Loma", logo: "queseria_la_loma.jpg" },
    { id: 3, auspiciante: "RM Automotores", logo: "rm_automotores.jpg" },
    { id: 12, auspiciante: "SL Amoblamientos", logo: "sl_amoblamientos.jpg" },
    { id: 40, auspiciante: "Super Nacha", logo: "super_nacha.jpg" },
    { id: 41, auspiciante: "Super Silvia", logo: "super_silvia.jpg" },
    { id: 19, auspiciante: "Taller Electromecánico Bari", logo: "taller_electromecanico_bari.jpg" },
    { id: 21, auspiciante: "Transporte Tachuela", logo: "transporte_tachuela.jpg" },
    { id: 2, auspiciante: "Veterinaria Vasco Viejo", logo: "vet_vasco_viejo.jpg" }
];

